[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@foundry-devops/=lib/foundry-devops/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
    ]

# Allow foundry to run commands on the command line
ffi = true 
fs_permissions = [{ access = "read", path = "./broadcast" }]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"

[fuzz]
runs = 100

[invariant]
runs = 128
depth = 128
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config