[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "cancun"
optimize = true
optimizer_runs = 200
remappings = [
    "@foundry-devops/=lib/foundry-devops/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@uniswap/v3-core/contracts/=lib/v3-core/contracts/",
    "@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/",
    "@uniswap/swap-router-contracts/=lib/swap-router-contracts/",
    "@aave/aave-v3-core/contracts/=lib/aave-v3-core/contracts/",
    ]

# Allow foundry to run commands on the command line
ffi = true 
fs_permissions = [{ access = "read", path = "./broadcast" }]

[fuzz]
runs = 100

[invariant]
runs = 128
depth = 128
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config